production:
  type: k8s
  bundle:
    registry: quay.io
    organization: operatorhubio
  index:
    registry: quay.io
    organization: operatorhubio
    name: catalog
    tags:
      - latest
    latest: latest
    signature: 0
  mirror:
    enabled: 0
    multiarch:
      base: registry.redhat.io/openshift4/ose-operator-registry:v4.5
      base_tags:
        - v4.5
        - v4.6
        - v4.7
      postfix: s
    registry: quay.io
    organization: operatorhubio
    name: catalog_prod
    username:
      in: jbreza
      out: framework_automation

pipeline:
  base: https://github.com
  repo: k8s-operatorhub/community-operators
  branch: main
  ci_scripts_dir: https://raw.githubusercontent.com/redhat-openshift-ecosystem/community-operators-pipeline/ci/latest/ci/scripts
  image: quay.io/operator_testing/operator-test-playbooks:latest
  playbooks:
    repo: https://github.com/redhat-openshift-ecosystem/operator-test-playbooks
    branch: "upstream-community"
  automerge:
    enabled: 1
  reviewers:
    enabled: 1
  notifications:
    slack: 1

operatorhubio:
  enabled: 1
  registry: quay.io
  organization: operator-framework
  name: upstream-community-operators
  tag: latest

#base:
#  organisation: operator-framework
#  project: operator-test-playbooks
#  tag: master
tools:
  kind_version: v0.9.0
  kind_kube_version: v1.21.1
  operator_sdk_version: v1.8.0
